version: "3"
services:
  ui:
    env_file:
      - .ui/.env
    build:
      context: ./ui/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - ui-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "12222:8000"
      - "13333:8080"
  scenario-server:
    env_file:
      - ./scenario-server/.env
    build:
      context: ./scenario-server/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - scenario-server-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "14444:3000"
  api-server:
    env_file:
      - ./api-server/.env
    build:
      context: ./api-server/.devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - api-server-extensions:/root/.vscode-server
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "15555:5000"
  etcd:
    image: bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  # ui-extensions:
  # scenario-server-extensions:
  # api-server-extensions:
  etcd_data:
