apiVersion: v1
data:
  db.json: |
    {
      "sentence":[
        { "title": "mock_title"}
      ],
      "summary": [
        { "body": "適当なテキスト"}
      ],
      "word": [
       {"words": ["a", "b", "c"]}
      ],
      "qiita": [
        {"body": "mock_content"}
      ]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mock-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apiserver-mock
  name: apiserver-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver-mock
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apiserver-mock
    spec:
      containers:
      - image: iaoiui0727/paisen-apiserver-mock
        name: paisen-apiserver-mock
        resources: {}
        volumeMounts:
        - name: mock-data
          mountPath: /data
      volumes:
      - name: mock-data
        configMap:
          name: mock-data
status: {}
--- 
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apiserver-mock
  name: api-server
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: apiserver-mock
status:
  loadBalancer: {}
